// Azure Front Door Premium in front of the web app (opt-in: `deployFrontDoor`
// in main.bicep). Operating procedure: docs/FRONT_DOOR_RUNBOOK.md.
//
// What this gives the white-label platform:
//   - One edge for every broker hostname. Each customer domain is a
//     `customDomains` entry with a Front Door-managed certificate, bound to the
//     routes below.
//   - A WAF policy (managed Default Rule Set + Bot Manager) on every domain.
//   - The public host the browser used, in `X-Inspro-Edge-Host`. The origin
//     host header stays the App Service default hostname (App Service routes by
//     Host), so the app restores the public host from this header — trusted only
//     when `X-Azure-FDID` equals INSPRO_FRONT_DOOR_ID (core/tenant_resolution.py).
//
// The origin lock (App Service access restriction) lives on the site itself in
// main.bicep, because it is part of the site's siteConfig.

targetScope = 'resourceGroup'

@description('Resource name prefix, e.g. inspro-prod.')
param prefix string

@description('The App Service default hostname Front Door forwards to, e.g. inspro-portal.azurewebsites.net.')
param originHostName string

@description('WAF mode. Detection logs matches without blocking; Prevention blocks requests whose anomaly score reaches the threshold.')
@allowed(['Detection', 'Prevention'])
param wafMode string

@description('Hostnames to serve, as [{ hostname, firmSlug }]: hostname is fully qualified (prefer a subdomain; an apex cannot take a CNAME), firmSlug is the owning firm\'s broker_firms.slug and prefixes the resource name. Each needs a CNAME to the endpoint hostname and a _dnsauth TXT record before its certificate is issued.')
param customDomains array

@description('Log Analytics workspace that receives the WAF log and Front Door metrics.')
param logAnalyticsWorkspaceId string

// Front Door resource names allow letters, digits and hyphens; the WAF policy
// name allows letters and digits only.
var profileName = '${prefix}-afd'
var endpointName = prefix
var wafPolicyName = replace('${prefix}waf', '-', '')

resource profile 'Microsoft.Cdn/profiles@2024-09-01' = {
  name: profileName
  location: 'global'
  // Premium, not Standard: the managed WAF rule sets (DRS 2.x, Bot Manager) are
  // Premium-only. Standard -> Premium is an in-place upgrade; there is no
  // downgrade path.
  sku: { name: 'Premium_AzureFrontDoor' }
  properties: {
    originResponseTimeoutSeconds: 60
  }
}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2024-09-01' = {
  parent: profile
  name: endpointName
  location: 'global'
  properties: {
    enabledState: 'Enabled'
    // The generated hostname (<name>-<hash>.<zone>.azurefd.net) stays the same
    // if the endpoint is deleted and recreated in this tenant, so broker CNAMEs
    // pointing at it survive a rebuild.
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2024-09-01' = {
  parent: profile
  name: 'app-service'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 50
    }
    // GET, not HEAD: the app's /health route is GET-only (FastAPI answers HEAD
    // with 405), and Front Door counts only a 200 as healthy. /health is exempt
    // from host resolution, so it answers without a firm. With a single origin
    // the probe affects metrics only — when every origin fails its probes Front
    // Door still routes to all of them
    // (https://learn.microsoft.com/azure/frontdoor/health-probes), so a long
    // interval keeps the probe load from every edge location low.
    healthProbeSettings: {
      probePath: '/health'
      probeRequestType: 'GET'
      probeProtocol: 'Https'
      probeIntervalInSeconds: 100
    }
    sessionAffinityState: 'Disabled'
  }
}

resource origin 'Microsoft.Cdn/profiles/originGroups/origins@2024-09-01' = {
  parent: originGroup
  name: 'web-app'
  properties: {
    hostName: originHostName
    // App Service selects the site by Host, so the origin host header must be
    // its default hostname (no customer domain is bound on App Service). The
    // public host travels in X-Inspro-Edge-Host instead.
    originHostHeader: originHostName
    httpPort: 80
    httpsPort: 443
    priority: 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
  }
}

resource ruleSet 'Microsoft.Cdn/profiles/ruleSets@2024-09-01' = {
  parent: profile
  name: 'EdgeHeaders'
}

// Order 1 and no conditions: runs first, on every request, on every route.
// `{hostname}` is the Front Door server variable for "the host name in the
// request from the client"
// (https://learn.microsoft.com/azure/frontdoor/rule-set-server-variables).
// Overwrite, not Append: a value the client sent in its own X-Inspro-Edge-Host
// is replaced, so the client cannot choose the host the app resolves.
resource edgeHostRule 'Microsoft.Cdn/profiles/ruleSets/rules@2024-09-01' = {
  parent: ruleSet
  name: 'SetEdgeHost'
  properties: {
    order: 1
    conditions: []
    actions: [
      {
        name: 'ModifyRequestHeader'
        parameters: {
          typeName: 'DeliveryRuleHeaderActionParameters'
          headerAction: 'Overwrite'
          headerName: 'X-Inspro-Edge-Host'
          value: '{hostname}'
        }
      }
    ]
    matchProcessingBehavior: 'Continue'
  }
}

// Resource names: `<firm-slug>--<hostname with dots as hyphens>`, the same
// formula infra/scripts/onboard_domain.py prints.
var customDomainNames = [for d in customDomains: '${toLower(d.firmSlug)}--${replace(toLower(d.hostname), '.', '-')}']

resource customDomain 'Microsoft.Cdn/profiles/customDomains@2024-09-01' = [for (d, i) in customDomains: {
  parent: profile
  name: customDomainNames[i]
  properties: {
    hostName: toLower(d.hostname)
    // Free, auto-renewing certificate. Issuance needs the _dnsauth TXT record,
    // and a CAA record on the broker's domain must allow the issuing CA.
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
    }
  }
}]

// By ID rather than `customDomain[i].id`, so each consumer below declares its
// dependency on the domains explicitly.
var customDomainRefs = [for n in customDomainNames: { id: resourceId('Microsoft.Cdn/profiles/customDomains', profileName, n) }]

// Everything except hashed bundle files: no caching. API responses are
// per-user, and index.html and the web manifest are branded per host
// (core/spa.py), so none of it may be shared from an edge cache.
resource defaultRoute 'Microsoft.Cdn/profiles/afdEndpoints/routes@2024-09-01' = {
  parent: endpoint
  name: 'default'
  properties: {
    originGroup: { id: originGroup.id }
    ruleSets: [{ id: ruleSet.id }]
    customDomains: customDomainRefs
    supportedProtocols: ['Http', 'Https']
    patternsToMatch: ['/*']
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Enabled'
    enabledState: 'Enabled'
    // No cacheConfiguration: caching is disabled on this route.
  }
  dependsOn: [
    origin
    edgeHostRule
    customDomain
  ]
}

// Vite's content-hashed files under /assets are identical on every host and
// served with `Cache-Control: public, max-age=31536000, immutable`, so the edge
// may cache them. The rule set is attached here too: the app resolves the host
// on these requests as well.
resource assetsRoute 'Microsoft.Cdn/profiles/afdEndpoints/routes@2024-09-01' = {
  parent: endpoint
  name: 'assets'
  properties: {
    originGroup: { id: originGroup.id }
    ruleSets: [{ id: ruleSet.id }]
    customDomains: customDomainRefs
    supportedProtocols: ['Http', 'Https']
    patternsToMatch: ['/assets/*']
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Enabled'
    enabledState: 'Enabled'
    cacheConfiguration: {
      queryStringCachingBehavior: 'IgnoreQueryString'
      compressionSettings: {
        isCompressionEnabled: true
        contentTypesToCompress: [
          'application/javascript'
          'text/javascript'
          'text/css'
          'image/svg+xml'
          'application/json'
          'font/woff2'
        ]
      }
    }
  }
  dependsOn: [
    origin
    edgeHostRule
    customDomain
  ]
}

resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2024-02-01' = {
  name: wafPolicyName
  location: 'Global'
  sku: { name: 'Premium_AzureFrontDoor' }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: wafMode
      requestBodyCheck: 'Enabled'
    }
    managedRules: {
      managedRuleSets: [
        {
          // DRS 2.x scores anomalies: a request is acted on once its score
          // reaches 5, and only in Prevention mode. 2.2 also exists; moving to
          // it is a deliberate re-tuning step, not a side effect of a deploy.
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.1'
        }
      ]
    }
  }
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2024-09-01' = {
  parent: profile
  name: 'waf'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: { id: wafPolicy.id }
      associations: [
        {
          // Every domain the routes serve: the azurefd.net endpoint and each
          // custom domain. A domain left out here would bypass the WAF.
          domains: concat([{ id: endpoint.id }], customDomainRefs)
          patternsToMatch: ['/*']
        }
      ]
    }
  }
  dependsOn: [
    customDomain
  ]
}

// The WAF log is what Detection mode is for: tuning reads it before the switch
// to Prevention. The per-request access log is deliberately not shipped — it
// would duplicate the app's own request telemetry at Log Analytics ingestion
// prices; add the FrontDoorAccessLog category while investigating if needed.
resource frontDoorDiag 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  scope: profile
  name: 'to-law'
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: [
      { category: 'FrontDoorWebApplicationFirewallLog', enabled: true }
      { category: 'FrontDoorHealthProbeLog', enabled: true }
    ]
    metrics: [
      { category: 'AllMetrics', enabled: true }
    ]
  }
}

@description('The profile\'s Front Door ID, sent to the origin as X-Azure-FDID.')
output frontDoorId string = profile.properties.frontDoorId

@description('The endpoint hostname brokers point their CNAME records at.')
output endpointHostName string = endpoint.properties.hostName

output profileName string = profile.name
output endpointName string = endpoint.name
