"""Regenerate category matching rules from their stored descriptions.

The category ``matching_rule`` is generated by ``rule_generator`` at slip-parse
time. When the generator improves (e.g. it learns to expand job-category code
ranges like "A1 to A9"), already-parsed categories keep their stale rule until
the slip is re-parsed. This backfill recomputes the rule in place from each
category's ``raw_description`` so existing policy years pick up the improvement
without a re-upload.

Multi-tenant: on Postgres each broker firm's ``categories`` live in a per-firm
``firm_<id>`` schema, so this iterates every firm and sets the search_path per
firm (mirrors ``provision_tenants.py``). On SQLite it runs once over the single
schema.

Safety:
- Only ``system_generated`` categories that are NOT ``human_modified`` are
  touched — manual edits and confirmed setups are never clobbered.
- ``status`` is left untouched (this never auto-confirms or auto-rejects a row).
- Dry-run by default: prints what WOULD change. Pass ``--apply`` to commit
  (committed per firm so a failure in one firm doesn't roll back the rest).

Usage:
    uv run python -m scripts.regenerate_category_rules            # dry-run, all PYs
    uv run python -m scripts.regenerate_category_rules --policy-year <id>
    uv run python -m scripts.regenerate_category_rules --apply
"""
from __future__ import annotations

import argparse

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.session import SessionLocal, engine
from app.db.tenancy import is_postgres, set_search_path
from app.models import BrokerFirm
from app.models.category import Category, CategoryStatus, SourceKind
from app.services.rule_generator import description_to_rule


def _regenerate_session(
    db: Session, policy_year_id: str | None, apply: bool
) -> tuple[int, int, int]:
    """Recompute rules within the session's current schema/search_path.

    Returns ``(changed, examined, job_category_rules)``. Does not commit — the
    caller owns the transaction so it can scope commits per firm.
    """
    changed = examined = job_category_rules = 0
    stmt = select(Category).where(
        Category.source == SourceKind.system_generated.value,
        Category.human_modified.is_(False),
    )
    if policy_year_id:
        stmt = stmt.where(Category.policy_year_id == policy_year_id)

    for cat in db.execute(stmt).scalars():
        source_text = cat.raw_description or cat.display_name
        if not source_text:
            continue
        examined += 1
        env = description_to_rule(source_text)
        if env.rule == cat.matching_rule:
            continue
        changed += 1
        if env.rule is not None and "job_category" in str(env.rule):
            job_category_rules += 1
        print(
            f"[{'APPLY' if apply else 'DRY '}] {cat.id} "
            f"{(cat.display_name or '')[:48]!r}\n"
            f"        old: {cat.matching_rule}\n"
            f"        new: {env.rule}"
        )
        if apply:
            cat.matching_rule = env.rule
            cat.rule_human_readable = env.human_readable
            cat.confidence = env.confidence
            cat.status = (
                cat.status
                if cat.status == CategoryStatus.confirmed.value
                else (
                    CategoryStatus.needs_review.value
                    if env.needs_review
                    else cat.status
                )
            )
    return changed, examined, job_category_rules


def regenerate(policy_year_id: str | None, apply: bool) -> int:
    """Regenerate across every firm schema (Postgres) or the single schema
    (SQLite). Returns the total number of categories whose rule changed."""
    changed = examined = job_category_rules = 0

    if is_postgres(engine):
        with SessionLocal() as db:
            firm_ids = list(db.execute(select(BrokerFirm.id)).scalars().all())
        for fid in firm_ids:
            with SessionLocal() as db:
                set_search_path(db, fid)
                c, e, j = _regenerate_session(db, policy_year_id, apply)
                if apply:
                    db.commit()
            changed += c
            examined += e
            job_category_rules += j
        scope = f"{len(firm_ids)} firm schema(s)"
    else:
        with SessionLocal() as db:
            changed, examined, job_category_rules = _regenerate_session(
                db, policy_year_id, apply
            )
            if apply:
                db.commit()
        scope = "single schema (SQLite)"

    verb = "updated" if apply else "would update"
    print(f"\n{verb} {changed} of {examined} regenerable categories across {scope}.")
    if not apply and changed:
        print("Re-run with --apply to persist, then re-run matching.")
    if job_category_rules:
        print(
            f"\nNOTE: {job_category_rules} regenerated rule(s) reference `job_category`, "
            "which is derived from the roster Job Grade column. Employees whose roster "
            "was uploaded before Job Grade was captured will NOT match these rules until "
            "their roster is re-uploaded (or job_grade back-filled) and matching is "
            "re-run — otherwise those (often senior) employees go silently unmatched."
        )
    return changed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policy-year", dest="policy_year", default=None)
    parser.add_argument("--apply", action="store_true", help="commit changes")
    args = parser.parse_args()
    regenerate(args.policy_year, args.apply)


if __name__ == "__main__":
    main()
