"""Allowlisted placeholders and escaped formatting; never evaluates template code."""

import re
from html import escape
from urllib.parse import urlsplit

from app.schemas.email_templates import Audience, BrandingContent, Purpose, TemplateContent

TOKEN = re.compile(r"{{\s*([a-z_]+)\s*}}")
EMAIL = re.compile(
    r"^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$"
)
FIELDS = {
    "company_name": "Company name",
    "recipient_name": "Recipient name",
    "recipient_first_name": "First name",
    "recipient_email": "Recipient email",
    "staff_id": "Staff ID",
    "login_identifier": "Sign-in ID",
    "portal_url": "Portal sign-in URL",
    "sender_display_name": "Sender name",
    "support_email": "Support email",
    "hr_role_label": "HR role",
    "activation_expires_at": "Link expiry (generated when sent)",
}


def valid_email(value: str) -> bool:
    local = value.partition("@")[0]
    return bool(
        len(value) <= 254
        and len(local) <= 64
        and EMAIL.fullmatch(value)
        and ".." not in value
        and not local.startswith(".")
        and not local.endswith(".")
    )


def valid_url(value: str) -> bool:
    try:
        url = urlsplit(value)
        return bool(
            url.scheme == "https"
            and url.hostname
            and not url.username
            and not url.password
            and not re.search(r"[\s<>{}\x00-\x1f\x7f]", value)
        )
    except ValueError:
        return False


def allowed_fields(content: TemplateContent) -> dict[str, str]:
    excluded = {"hr_role_label"} if content.audience == "employee" else {"staff_id"}
    if content.purpose == "general":
        excluded.add("activation_expires_at")
    return {key: label for key, label in FIELDS.items() if key not in excluded}


def validate_content(content: TemplateContent) -> dict[str, str]:
    errors: dict[str, str] = {}
    fields = allowed_fields(content)
    for name in ("title", "subject", "body"):
        if not getattr(content, name).strip():
            errors[name] = f"Enter a {name.replace('_', ' ')}."
    for name in ("subject", "preheader", "body", "button_label", "button_url"):
        value = str(getattr(content, name))
        unknown = sorted(set(TOKEN.findall(value)) - fields.keys())
        remainder = TOKEN.sub("", value)
        if unknown:
            errors[name] = "Unsupported placeholder: " + ", ".join(unknown) + "."
        elif "{" in remainder or "}" in remainder:
            errors[name] = "Use a supported placeholder in the form {{field_name}}."
        if re.search(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", value):
            errors[name] = "Remove control characters."
        if name != "body" and re.search(r"[\r\n]", value):
            errors[name] = "Use a single line."
    if re.search(r"[\r\n\x00-\x1f\x7f{}]", content.title):
        errors["title"] = "Use a single-line title without placeholders."
    if re.search(r"<\s*/?\s*[a-z!]", content.body, re.I):
        errors["body"] = "Use the formatting controls; HTML tags are not supported."
    for _label, url in re.findall(r"\[([^\]]+)\]\(([^)]+)\)", content.body):
        if not valid_url(url) and url != "{{portal_url}}":
            errors["body"] = "Links must use HTTPS or {{portal_url}}."
    if content.purpose == "general":
        if bool(content.button_label.strip()) != bool(content.button_url.strip()):
            errors["button_label"] = (
                "Enter both a button label and destination, or leave both blank."
            )
        if (
            content.button_url
            and content.button_url != "{{portal_url}}"
            and not valid_url(content.button_url)
        ):
            errors["button_url"] = "Use an HTTPS URL or {{portal_url}}."
    else:
        if not content.button_label.strip():
            errors["button_label"] = "Enter the account-setup button label."
        if content.button_url:
            errors["button_url"] = "Account-setup destinations are generated by the system."
    return errors


def validate_branding(content: BrandingContent) -> dict[str, str]:
    errors = {}
    if not content.sender_display_name.strip() or re.search(
        r"[\r\n\x00-\x1f\x7f{}]", content.sender_display_name
    ):
        errors["sender_display_name"] = "Enter a single-line sender name without placeholders."
    if not valid_email(content.support_email):
        errors["support_email"] = "Enter a valid support email address."
    if content.logo_url and not valid_url(content.logo_url):
        errors["logo_url"] = "Use an HTTPS logo URL."
    if "{{" in content.footer or "}}" in content.footer:
        errors["footer"] = "Footer text does not support placeholders."
    return errors


def expand(value: str, context: dict[str, str]) -> str:
    return TOKEN.sub(lambda match: context.get(match[1], f"[Missing: {match[1]}]"), value)


def validate_values(content: TemplateContent, context: dict[str, str]) -> dict[str, str]:
    """Check actual data too: a safe template can expand to missing/unsafe values."""
    errors = {}
    for name in ("subject", "preheader", "body", "button_label", "button_url"):
        source = str(getattr(content, name))
        missing = sorted(
            key for key in set(TOKEN.findall(source)) if not context.get(key, "").strip()
        )
        if missing:
            errors[name] = "Missing recipient data: " + ", ".join(missing) + "."
        value = expand(source, context)
        if re.search(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", value):
            errors[name] = "Recipient data contains unsupported control characters."
        elif name != "body" and re.search(r"[\r\n]", value):
            errors[name] = "Recipient data must resolve to a single line."
        limit = {
            "subject": 200,
            "preheader": 200,
            "body": 100000,
            "button_label": 120,
            "button_url": 2000,
        }[name]
        if len(value) > limit:
            errors[name] = f"Resolved content exceeds {limit:,} characters."
    return errors


def inline(value: str) -> str:
    """Format escaped text only. Variables cannot inject markup or links."""
    value = escape(value)
    value = re.sub(r"\*\*([^*\n]+)\*\*", r"<strong>\1</strong>", value)
    value = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", value)
    return value


def body_html(source: str, context: dict[str, str]) -> str:
    # Format source first, then substitute escaped values. This also allows
    # **{{recipient_name}}** without interpreting markup inside the name.
    def text_html(line: str) -> str:
        return TOKEN.sub(
            lambda match: escape(context.get(match[1], f"[Missing: {match[1]}]")), inline(line)
        )

    def line_html(line: str) -> str:
        result = ""
        cursor = 0
        for match in re.finditer(r"\[([^\]\n]+)\]\(([^)]+)\)", line):
            result += text_html(line[cursor : match.start()])
            url = expand(match[2], context)
            label = text_html(match[1])
            result += (
                f'<a href="{escape(url, quote=True)}" rel="noreferrer">{label}</a>'
                if valid_url(url)
                else label
            )
            cursor = match.end()
        return result + text_html(line[cursor:])

    paragraphs = []
    for paragraph in source.split("\n\n"):
        lines = paragraph.splitlines()
        if lines and all(line.startswith("- ") for line in lines):
            paragraphs.append(
                "<ul>" + "".join(f"<li>{line_html(line[2:])}</li>" for line in lines) + "</ul>"
            )
        else:
            paragraphs.append("<p>" + "<br>".join(line_html(line) for line in lines) + "</p>")
    return "".join(paragraphs)


def render(
    content: TemplateContent, branding: BrandingContent, context: dict[str, str]
) -> dict[str, str]:
    subject = expand(content.subject, context)
    plain = re.sub(r"\[([^\]\n]+)\]\(([^)]+)\)", r"\1 (\2)", content.body)
    plain = re.sub(r"\*\*([^*\n]+)\*\*", r"\1", plain)
    plain = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"\1", plain)
    text = expand(plain, context)
    body = body_html(content.body, context)
    if content.purpose != "general":
        identity = context.get("login_identifier", "[Assigned when invitation is sent]")
        expiry = context.get("activation_expires_at", "[Generated when sent]")
        body += f"<p>Sign-in ID: <strong>{escape(identity)}</strong></p>"
        body += f"<p>{escape(expiry)}</p>"
        text += f"\n\nSign-in ID: {identity}\n{expiry}"
    if content.button_label:
        label = expand(content.button_label, context)
        # Previews never contain a usable credential link, including for real recipients.
        url = expand(content.button_url, context) if content.purpose == "general" else ""
        safe_url = url if valid_url(url) else "#"
        body += (
            f'<p><a class="button" href="{escape(safe_url, quote=True)}">{escape(label)}</a></p>'
        )
        text += f"\n\n{label}: {url or '[Personal setup link generated only when sending]'}"
    footer = branding.footer.strip()
    text += f"\n\nNeed help? {branding.support_email}"
    if footer:
        text += f"\n{footer}"
    html = (
        '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Email preview</title>'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        '<meta http-equiv="Content-Security-Policy" '
        "content=\"default-src 'none'; style-src 'unsafe-inline'; img-src https:\">"
        "<style>body{margin:0;background:#f5f3f1;color:#242424;font:16px/1.65 Arial,sans-serif;"
        "overflow-wrap:anywhere}main{max-width:560px;margin:auto;padding:32px 24px;"
        "background:white}"
        "p{margin:0 0 20px}a{color:#a11625}.button{display:inline-block;background:#b51929;"
        "color:white;padding:12px 20px;border-radius:6px;text-decoration:none}"
        "footer{font-size:13px;color:#555;border-top:1px solid #ddd;padding-top:20px}</style>"
        "</head><body><main>"
        + '<div style="display:none;max-height:0;overflow:hidden;opacity:0">'
        + f"{escape(expand(content.preheader, context))}</div>"
        + (
            f'<p><img src="{escape(branding.logo_url, quote=True)}" '
            'alt="Company logo" width="160" style="max-width:100%;height:auto" '
            'referrerpolicy="no-referrer"></p>'
            if branding.logo_url
            else ""
        )
        + f"<p><strong>{escape(branding.sender_display_name)}</strong></p>{body}"
        f"<footer>Need help? {escape(branding.support_email)}<br>{escape(footer)}</footer>"
        "</main></body></html>"
    )
    return {
        "subject": subject,
        "preheader": expand(content.preheader, context),
        "html": html,
        "text": text,
    }


def starters() -> dict[str, TemplateContent]:
    result = {}
    audiences: list[tuple[Audience, str]] = [("employee", "Employee"), ("hr", "HR")]
    purposes: list[tuple[Purpose, str]] = [
        ("invitation", "welcome"),
        ("password_reset", "password setup"),
    ]
    for audience, label in audiences:
        for purpose, suffix in purposes:
            result[f"{audience}_{purpose}"] = TemplateContent(
                title=f"{label} {suffix}",
                audience=audience,
                purpose=purpose,
                subject="Your {{company_name}} "
                + ("benefits portal account" if audience == "employee" else "HR portal account"),
                preheader="Set your password to access your account.",
                body="Hello {{recipient_name}},\n\n"
                + (
                    "Your account for {{company_name}} is ready to set up."
                    if purpose == "invitation"
                    else "A password setup or reset was requested for your account "
                    "at {{company_name}}."
                )
                + "\n\nChoose your own password using the button below.\n\n"
                "If you were not expecting this email, contact {{support_email}}.",
                button_label="Set up my account" if purpose == "invitation" else "Set my password",
            )
    return result
