"""initial schema

Revision ID: 1a54b8d5880e
Revises: 
Create Date: 2026-05-12 14:00:03.138300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.migration_helpers import json_variant


revision: str = '1a54b8d5880e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_firms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_firms'))
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('broker_firm_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_firm_id'], ['broker_firms.id'], name=op.f('fk_clients_broker_firm_id_broker_firms'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('before', json_variant(), nullable=True),
    sa.Column('after', json_variant(), nullable=True),
    sa.Column('cross_tenant_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_audit_log_client_id_clients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('employee_attribute_schemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True, comment='null = global Singapore default'),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('enum_values', json_variant(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('derived_from', sa.String(length=64), nullable=True),
    sa.Column('derivation_rule', json_variant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_employee_attribute_schemas_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_attribute_schemas'))
    )
    with op.batch_alter_table('employee_attribute_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_attribute_schemas_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_attribute_schemas_client_id'), ['client_id'], unique=False)

    op.create_table('policy_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='policyyearstatus'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.String(length=36), nullable=True),
    sa.Column('snapshot_json', json_variant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_policy_years_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_years')),
    sa.UniqueConstraint('client_id', 'year', name='uq_policy_year')
    )
    with op.batch_alter_table('policy_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_years_client_id'), ['client_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('insurer', sa.String(length=128), nullable=True),
    sa.Column('participation_model', sa.Enum('standard', 'extended', 'eo_only', name='participationmodel'), nullable=False),
    sa.Column('has_dependants', sa.Boolean(), nullable=False),
    sa.Column('is_outpatient', sa.Boolean(), nullable=False),
    sa.Column('product_metadata', json_variant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_products_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_year_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('raw_description', sa.String(length=2048), nullable=False),
    sa.Column('matching_rule', json_variant(), nullable=True),
    sa.Column('rule_human_readable', sa.String(length=1024), nullable=True),
    sa.Column('participation_model', sa.String(length=64), nullable=True),
    sa.Column('plan_assignments', json_variant(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'ai_extracted', 'csv_import', name='sourcekind'), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'needs_review', 'confirmed', name='categorystatus'), nullable=False),
    sa.Column('human_modified', sa.Boolean(), nullable=False),
    sa.Column('modified_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_year_id'], ['policy_years.id'], name=op.f('fk_categories_policy_year_id_policy_years'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_categories_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_policy_year_id'), ['policy_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    op.create_table('placement_slips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_year_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('blob_url', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('parse_status', sa.Enum('pending', 'parsing', 'parsed', 'error', name='parsestatus'), nullable=False),
    sa.Column('parse_log', json_variant(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_year_id'], ['policy_years.id'], name=op.f('fk_placement_slips_policy_year_id_policy_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_slips'))
    )
    with op.batch_alter_table('placement_slips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_slips_policy_year_id'), ['policy_year_id'], unique=False)

    op.create_table('plan_attribute_schemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('attribute_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_plan_attribute_schemas_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_attribute_schemas'))
    )
    with op.batch_alter_table('plan_attribute_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_attribute_schemas_product_id'), ['product_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('policy_year_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=128), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('attribute_values', json_variant(), nullable=False),
    sa.Column('derived_attribute_values', json_variant(), nullable=False),
    sa.Column('matched_category_id', sa.String(length=36), nullable=True),
    sa.Column('match_method', sa.String(length=32), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_employees_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_category_id'], ['categories.id'], name=op.f('fk_employees_matched_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_year_id'], ['policy_years.id'], name=op.f('fk_employees_policy_year_id_policy_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_name'), ['employee_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_matched_category_id'), ['matched_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_policy_year_id'), ['policy_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_staff_id'), ['staff_id'], unique=False)

    op.create_table('dependants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('policy_year_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('attribute_values', json_variant(), nullable=False),
    sa.Column('link_method', sa.String(length=32), nullable=True, comment='staff_id | id_no | name | unlinked'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_dependants_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_dependants_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_year_id'], ['policy_years.id'], name=op.f('fk_dependants_policy_year_id_policy_years'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependants'))
    )
    with op.batch_alter_table('dependants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependants_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependants_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependants_policy_year_id'), ['policy_year_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependants_policy_year_id'))
        batch_op.drop_index(batch_op.f('ix_dependants_employee_id'))
        batch_op.drop_index(batch_op.f('ix_dependants_client_id'))

    op.drop_table('dependants')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_staff_id'))
        batch_op.drop_index(batch_op.f('ix_employees_policy_year_id'))
        batch_op.drop_index(batch_op.f('ix_employees_matched_category_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_name'))
        batch_op.drop_index(batch_op.f('ix_employees_client_id'))

    op.drop_table('employees')
    with op.batch_alter_table('plan_attribute_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_attribute_schemas_product_id'))

    op.drop_table('plan_attribute_schemas')
    with op.batch_alter_table('placement_slips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_slips_policy_year_id'))

    op.drop_table('placement_slips')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))
        batch_op.drop_index(batch_op.f('ix_categories_product_id'))
        batch_op.drop_index(batch_op.f('ix_categories_policy_year_id'))

    op.drop_table('categories')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_code'))
        batch_op.drop_index(batch_op.f('ix_products_client_id'))

    op.drop_table('products')
    with op.batch_alter_table('policy_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_years_client_id'))

    op.drop_table('policy_years')
    with op.batch_alter_table('employee_attribute_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_attribute_schemas_client_id'))
        batch_op.drop_index(batch_op.f('ix_employee_attribute_schemas_attribute_id'))

    op.drop_table('employee_attribute_schemas')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('clients')
    op.drop_table('broker_firms')
    # ### end Alembic commands ###
