import type { Content } from "./types";

export function validEmail(value: string): boolean {
  const local = value.split("@")[0];
  return value.length <= 254 && local.length <= 64 && !local.startsWith(".") && !local.endsWith(".") && !value.includes("..") &&
    /^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$/.test(value);
}

export function fieldsFor(content: Content, fields: Record<string, string>) {
  return Object.fromEntries(Object.entries(fields).filter(([key]) =>
    !(key === "hr_role_label" && content.audience === "employee") &&
    !(key === "staff_id" && content.audience === "hr") &&
    !(key === "activation_expires_at" && content.purpose === "general")));
}
export function validUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && !!url.hostname && !url.username && !url.password &&
      !/[\s<>{}\x00-\x1f\x7f]/.test(value);
  } catch { return false; }
}
export function validate(content: Content, fields: Record<string, string>): Record<string, string> {
  const errors: Record<string, string> = {};
  const allowed = fieldsFor(content, fields);
  for (const key of ["title", "subject", "body"] as const) {
    if (!content[key].trim()) errors[key] = `Enter a ${key}.`;
  }
  const limits = { title: 120, subject: 200, preheader: 200, body: 20000, button_label: 60, button_url: 2000 };
  for (const [key, limit] of Object.entries(limits)) {
    const value = content[key as keyof Content];
    if (value.length > limit) errors[key] = `Use ${limit.toLocaleString()} characters or fewer.`;
    if (key !== "body" && /[\r\n]/.test(value)) errors[key] = "Use a single line.";
    if (/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value)) errors[key] = "Remove control characters.";
    if (key === "title") {
      if (/[{}]/.test(value)) errors[key] = "Template titles cannot contain placeholders.";
      continue;
    }
    const matches = [...value.matchAll(/{{\s*([a-z_]+)\s*}}/g)];
    const unknown = [...new Set(matches.map(m => m[1]).filter(k => !(k in allowed)))];
    if (unknown.length) errors[key] = `Unsupported placeholder: ${unknown.join(", ")}.`;
    else if (/[{}]/.test(value.replace(/{{\s*([a-z_]+)\s*}}/g, "")))
      errors[key] = "Use a supported placeholder in the form {{field_name}}.";
  }
  if (/<\s*\/?\s*[a-z!]/i.test(content.body)) errors.body = "Use the formatting controls; HTML tags are not supported.";
  for (const link of content.body.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)) {
    if (!validUrl(link[2]) && link[2] !== "{{portal_url}}") errors.body = "Links must use HTTPS or {{portal_url}}.";
  }
  if (content.purpose === "general") {
    if (!!content.button_label.trim() !== !!content.button_url.trim()) errors.button_label = "Enter both a button label and destination, or leave both blank.";
    if (content.button_url && content.button_url !== "{{portal_url}}" && !validUrl(content.button_url))
      errors.button_url = "Use an HTTPS URL or {{portal_url}}.";
  } else {
    if (!content.button_label.trim()) errors.button_label = "Enter the account-setup button label.";
    if (content.button_url) errors.button_url = "Account-setup destinations are generated by the system.";
  }
  return errors;
}
